//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComosDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradeSubject()
        {
            this.GradeSubjectTopics = new HashSet<GradeSubjectTopic>();
            this.PostSchools = new HashSet<PostSchool>();
        }
    
        public int GradeSubjectID { get; set; }
        public int GS_GradeID { get; set; }
        public int GS_SubjectID { get; set; }
        public string GradeSubject_Description { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeSubjectTopic> GradeSubjectTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostSchool> PostSchools { get; set; }
    }
}
