//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComosDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicSubTopic
    {
        public int TopicSubTopicID { get; set; }
        public int TST_TopicID { get; set; }
        public int TST_SubTopicID { get; set; }
    
        public virtual SubTopic SubTopic { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
